# Generated by Django 5.0.1 on 2024-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=400)),
                ('rating', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('delivery', models.CharField(default='free delivery', max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
