# Generated by Django 5.0.1 on 2024-09-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_addtocart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="addtocart",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
