# Generated by Django 5.0.1 on 2024-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order_quantity_alter_addtocart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="addtocart",
            name="preference",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="review",
            field=models.TextField(blank=True, default="good", null=True),
        ),
    ]
